# Generated by Django 4.2.8 on 2026-06-03 22:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_risk', 'Paciente de alto risco'), ('symptom_spike', 'Pico de sintomas'), ('no_followup', 'Acompanhamento em atraso'), ('cluster', 'Concentração de casos')], max_length=20, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critical', 'Crítico')], default='warning', max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('dedup_key', models.CharField(max_length=200, unique=True, verbose_name='Chave de deduplicação')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Comorbidade')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Crítica')),
            ],
            options={
                'verbose_name': 'Comorbidade',
                'verbose_name_plural': 'Comorbidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente (APS)',
                'verbose_name_plural': 'Pacientes (APS)',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Sintoma')),
                ('is_respiratory', models.BooleanField(default=False, verbose_name='Respiratório')),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=datetime.date.today, verbose_name='Data da visita')),
                ('medications', models.TextField(blank=True, verbose_name='Medicações em uso')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('risk_level', models.CharField(blank=True, choices=[('baixo', 'Baixo risco'), ('medio', 'Médio risco'), ('alto', 'Alto risco')], max_length=10, verbose_name='Nível de risco')),
                ('risk_score', models.FloatField(blank=True, null=True, verbose_name='Score de risco (0-100)')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='Versão do modelo')),
                ('predicted_at', models.DateTimeField(blank=True, null=True, verbose_name='Previsto em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visita / Triagem',
                'verbose_name_plural': 'Visitas / Triagens',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Muito leve'), (2, 'Leve'), (3, 'Moderado'), (4, 'Grave'), (5, 'Muito grave')], default=3, verbose_name='Severidade')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Duração (dias)')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_symptoms', to='triage.symptom', verbose_name='Sintoma')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_symptoms', to='triage.visit', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Sintoma da visita',
                'verbose_name_plural': 'Sintomas da visita',
            },
        ),
    ]
