# Generated by Django 4.2.8 on 2026-06-03 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='acs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='ACS responsável'),
        ),
        migrations.AddField(
            model_name='visit',
            name='comorbidities',
            field=models.ManyToManyField(blank=True, related_name='visits', to='triage.comorbidity', verbose_name='Comorbidades'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='triage.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por (ACS)'),
        ),
        migrations.AddField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='triage.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='alert',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='triage.visit', verbose_name='Visita'),
        ),
        migrations.AlterUniqueTogether(
            name='visitsymptom',
            unique_together={('visit', 'symptom')},
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['-visit_date'], name='triage_visi_visit_d_014360_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['risk_level'], name='triage_visi_risk_le_b0de2e_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='triage_visi_patient_08122f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_resolved', '-created_at'], name='triage_aler_is_reso_29b3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='triage_aler_severit_474bd0_idx'),
        ),
    ]
