# Generated by Django 4.2.8 on 2026-06-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Sanguíneo')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Histórico Médico')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato de Emergência')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Emergência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.IntegerField(verbose_name='Pressão Sistólica (mmHg)')),
                ('blood_pressure_diastolic', models.IntegerField(verbose_name='Pressão Diastólica (mmHg)')),
                ('heart_rate', models.IntegerField(verbose_name='Frequência Cardíaca (bpm)')),
                ('temperature', models.FloatField(verbose_name='Temperatura (°C)')),
                ('weight', models.FloatField(verbose_name='Peso (kg)')),
                ('height', models.FloatField(verbose_name='Altura (cm)')),
                ('blood_glucose', models.FloatField(blank=True, null=True, verbose_name='Glicose (mg/dL)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Medido em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Sinais Vitais',
                'verbose_name_plural': 'Sinais Vitais',
                'ordering': ['-measured_at'],
            },
        ),
    ]
