# Generated by Django 4.2.8 on 2026-06-03 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='patientvitals',
            index=models.Index(fields=['-measured_at'], name='patients_pa_measure_f8339c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvitals',
            index=models.Index(fields=['patient', '-measured_at'], name='patients_pa_patient_5915da_idx'),
        ),
    ]
